config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  shallow do
    resources :boards do
      resources :lists do
        resources :tasks
        get 'tasks/:id/justification', to: 'tasks/justification#edit',
                                       as: 'justification'
      end
    end
  end

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  has_many :lists, dependent: :destroy

  enum visibility: { public: 0, private: 1 }, _prefix: true

  validates :name, presence: true
  validates :visibility, presence: true
end

app/models/concerns/task_validator.rb
# frozen_string_literal: true

class TaskValidator < ActiveModel::Validator
  def validate(record)
    need_finished_at(record) if record.finished_at.nil? && !record.justification.nil?

    return if record.finished_at.nil?

    if record.started_at.nil?
      need_started_at(record)
    elsif record.finished_at < record.started_at
      finished_at_lower_than(record)
    end
  end

  private

  def need_finished_at(record)
    record.errors.add(:justification, 'need finished_at first')
  end

  def need_started_at(record)
    record.errors.add(:finished_at, 'need started_at first')
  end

  def finished_at_lower_than(record)
    record.errors.add(:finished_at, "can't be lower than started_at")
  end
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :board

  enum color: { danger: 0, success: 1, warning: 2, info: 3,
                primary: 4, secondary: 5 }, _prefix: true
  enum priority: { Low: 0, Medium: 1, High: 3 }, _prefix: true

  validates :name, presence: true
  validates :color, presence: true
  validates :priority, presence: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  after_create :add_task_history
  before_update :add_task_history_update

  has_rich_text :details
  belongs_to :list
  has_many :task_histories, dependent: :destroy

  validates :title, presence: true
  validates_with TaskValidator

  def doing_time
    doing_time_in_seconds / 1.hour if doing_time_in_seconds
  end

  private

  def doing_time_in_seconds
    (finished_at - started_at).to_i
  rescue StandardError
    nil
  end

  def add_task_history
    TaskHistory.create(list: list.name, task_id: id)
  end

  def add_task_history_update
    add_task_history unless list_id == list_id_was
  end
end

app/models/task_history.rb
# frozen_string_literal: true

class TaskHistory < ApplicationRecord
  belongs_to :task

  validates :list, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController
  before_action :set_board, only: %i[show edit update destroy]

  def index
    @boards = Board.all
    # ActionCable.server.broadcast("board_channel", { data: board_render(@boards) })
    CreateBoardJob.perform_now(board_render(@boards))
  end

  def show
    redirect_to board_lists_path(@board)
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      flash[:success] = 'Board was created successfully'
      redirect_to boards_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @board.update(board_params)
      flash[:success] = 'Board was updated successfully'
      redirect_to boards_path
    else
      render 'new'
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private

  def board_params
    params.require(:board).permit(:name, :visibility)
  end

  def set_board
    @board = Board.find(params[:id])
  end

  def board_render(boards)
    render_to_string(partial: 'card', locals: { boards: boards })
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]
  before_action :board, only: %i[index new create]
  before_action :shallow_board, only: %i[update destroy]

  def index
    @lists = @board.lists
  end

  def show
    redirect_to list_tasks_path(@list)
  end

  def new
    @list = @board.lists.build
  end

  def create
    @list = @board.lists.build(list_params)
    if @list.save
      flash[:success] = 'List was created successfully'
      redirect_to board_lists_path(@board)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @list.update(list_params)
      flash[:success] = 'List was updated successfully'
      redirect_to board_lists_path(@board)
    else
      render 'new'
    end
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path(@board)
  end

  private

  def list_params
    params.require(:list).permit(:name, :color, :priority)
  end

  def set_list
    @list = List.find(params[:id])
  end

  def board
    @board = Board.find(params[:board_id])
  end

  def shallow_board
    @board = @list.board_id
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/controllers/tasks/justification_controller.rb
# frozen_string_literal: true

module Tasks
  class JustificationController < TasksController
    def edit; end
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :list, only: %i[index new create]
  before_action :shallow_list, only: %i[update destroy]

  def index
    @tasks = @list.tasks
  end

  def show; end

  def new
    @task = @list.tasks.build
    @lists = @list.board.lists
  end

  def create
    @task = @list.tasks.build(task_params)
    if @task.save
      flash[:success] = 'Task was created successfully'
      redirect_to board_lists_path(@list.board_id)
    else
      render 'new'
    end
  end

  def edit
    @lists = @task.list.board.lists
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'Task was updated successfully'
      redirect_to @task
    else
      render 'new'
    end
  end

  def destroy
    board = @task.list.board_id
    @task.destroy
    redirect_to board_lists_path(board)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details,
                                 :started_at, :finished_at, :justification, :list_id)
  end

  def list
    @list = List.find(params[:list_id])
  end

  def shallow_list
    @list = @task.list
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/task_helper.rb
# frozen_string_literal: true

module TaskHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/boards/_card.html.erb
<% @boards.each do |board| %>
<div class="card boards">
  <div class="card-body">
    <h5 class="card-title d-flex flex-row justify-content-between">
      <%= link_to board.name, board %>
      <div>
        <%= link_to icon('fa-regular', 'pen-to-square'),
          edit_board_path(board) %>
        <%= link_to icon('fa-solid', 'trash'),
          board_path(board), method: :delete,
          data: {confirm: "Are you sure?"} %>
      </div>
    </h5>
    <h6 class="card-subtitle mb-2">
      Priority: <%= board.visibility %>
    </h6>
    <p class="card-text">
      <% board.lists.each do |list|%>
        <div class="card border border-dark mb-1 p-1 d-flex flex-row justify-content-between">
          <div class='align-self-center'>
            <%= list.name %>
          </div>
          <div>
            <div class='bg-<%= list.color %> p-1 rounded'>
              Priority: <%= list.priority %>
            </div>
          </div>
        </div>
      <% end %>
    </p>
  </div>
</div>
<% end %>

app/views/boards/_form.html.erb
<%= form_with model: @board, remote: true do |f| %>
  <div class="mb-3 row">
    <%= f.label :name, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :visibility, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.select :visibility, Board.visibilities.keys.to_a%>
    </div>
  </div>

  <div class="col-auto">
    <%= f.submit class: "btn btn-success mb-3" %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit List: <%= @board.name %></h1>

<%= render 'form' %>

<%= link_to 'Go back', boards_path %>

app/views/boards/index.html.erb
<h1>Boards</h1>
<%= link_to 'New Board', new_board_path, class: 'btn btn-outline-success mb-3'%>

<div class="row cable-container">

    <%= render 'card' %>

</div>

<%= link_to 'Go home', root_path %>

app/views/boards/new.html.erb
<h1>Create a New Board</h1>

<%= render 'form' %>

<%= link_to 'Go back', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_card.html.erb
<div class="card bg-<%= list.color %> list-tasks">
  <div class="card-body">
    <h5 class="card-title d-flex flex-row justify-content-between">
      <%= link_to list.name, list %>
      <div>
        <%= link_to icon('fa-regular', 'pen-to-square'),
          edit_list_path(list, board_id: list.board) %>
        <%= link_to icon('fa-solid', 'trash'),
          list_path(list, board_id: list.board), method: :delete,
          data: {confirm: "Are you sure?"} %>
      </div>
    </h5>
    <h6 class="card-subtitle mb-2 text-light">
      Priority: <%= list.priority %>
    </h6>
    <p class="card-text">
      <%= link_to 'New Task', new_list_task_path(list), class: 'btn btn-success boder border-dark'%>
      <% list.tasks.each do |task|%>
        <div class="card border border-dark mb-1 p-1 d-flex flex-row justify-content-between">
          <div>
            <%= link_to task.title, task_path(task) %>
          </div>
          <div>
            <%= link_to icon('fa-solid', 'pen-to-square'),
              edit_task_path(task) %>
            <%= link_to icon('fa-solid', 'trash'),
              task_path(task), method: :delete,
              data: {confirm: "Are you sure?"} %>
          </div>
        </div>
      <% end %>
    </p>
  </div>
</div>

app/views/lists/_form.html.erb
<%= form_with model: [ @board, @list] do |f| %>
  <div class="mb-3 row">
    <%= f.label :name, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :color, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.select :color, [
          ['Green','success'],['Red','danger'],['Blue','info'],
          ['Yellow','warning']
        ]%>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :priority, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.select :priority, [
          'High', 'Medium', 'Low'
        ]%>
    </div>
  </div>

  <div class="col-auto">
    <%= f.submit class: "btn btn-success mb-3" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List: <%= @list.name %></h1>

<%= render 'form' %>

<%= link_to 'Go back', board_lists_path(@list.board_id) %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<%= link_to 'New List', new_board_list_path, class: 'btn btn-outline-success mb-3'%>
<%= link_to 'Return', boards_path, class: 'btn btn-outline-secondary mb-3'%>
<div class="row">
  <% @lists.each do |list| %>
    <%= render 'card', list: list %>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>Create a New List</h1>

<%= render 'form' %>

<%= link_to 'Go back', board_lists_path(@board) %>

app/views/pages/home.html.erb
<h1>Welcome to Home</h1>

<%= link_to 'Go to Boards', boards_path %>

app/views/tasks/_card.html.erb
<% @presenter = TaskPresenter.new(task) %>
<div class="card mt-4 mb-2">
  <div class="card-header ">
    <b>Anonymous</b>
    <small class="text-muted d-flex">
        <div class= "p-2">
          <b>Started at: </b><%= @presenter.started_at? %>
        </div>
        <div class= "p-2">
          <b>Finished at: </b> <%= @presenter.finished_at? %>
        </div>
        <div class= "p-2">
          <%= @presenter.doing_time? %>
        </div>
    </small>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= task.title %></h5>
    <div class="card-text trix-content mb-2 list-group">
      <div class="list-group-item">
        <%= task.details %>
      </div>
      <div class="list-group-item bg-secondary bg-opacity-25">
        <%= @presenter.justification? %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <small class="text-muted">
      <b>Created at: </b><%= task.created_at %> |
      <b>Edited at: </b> <%= task.updated_at %>
    </small>
    <small class="text-muted">
      <h4>History</h4>
      <% task.task_histories.each do |history| %>
        <div>
          Moved to <%= history.list %> on <%= history.created_at %>
        </div>
      <% end %>
    </small>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: [ @list, @task ] do |f| %>
  <div class="mb-3 row">
    <%= f.label :title, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label :details, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.rich_text_area :details, class: "form-control" %>
    </div>
  </div>

  <div class="mb-3 row">
    <%= f.label 'Select list', class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :list_id, @lists, :id, :name, class: "form-control"%>
    </div>
  </div>

  <div class="col-auto">
    <%= f.submit class: "btn btn-success mb-3" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task: <%= @task.title %></h1>

<%= render 'form' %>

<%= link_to 'Go back', :back %>

app/views/tasks/index.html.erb
<h1>Lista: <%= @list.name %></h1>

<%= link_to 'Create New Task', new_list_task_path, class: "btn btn-success mb-3"%>
<%= link_to 'Return', board_lists_path(@list.board_id), class: 'btn btn-outline-secondary mb-3'%>

<% @tasks.each do |task| %>
  <%= render 'card', task: task %>
  <div>
    <%= link_to 'Delete', task_path(task), method: :delete, data: {confirm: "Are you sure?"}, class:'btn btn-danger'%>
    <%= link_to 'Show', task_path(task), class:'btn btn-outline-info'%>
  </div>
<% end %>

app/views/tasks/justification/edit.html.erb
<%= render 'card', task: @task %>

<%= form_with model: @task do |f| %>
  <div class="mb-3 row">
    <%= f.label :justification, class:"col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= f.text_area :justification, class: "form-control" %>
    </div>
  </div>

  <div class="col-auto">
    <%= f.submit class: "btn btn-success mb-3" %>
  </div>
<% end %>

<%= link_to 'Go back', @task %>

app/views/tasks/new.html.erb
<h1>Please Create a New Task</h1>

<%= render 'form' %>

<%= link_to 'Go back', board_lists_path(@list.board_id) %>

app/views/tasks/show.html.erb
<%= render 'card', task: @task%>

<div class="mb-3">
  <%= link_to 'Edit', edit_task_path(@task),
    class:'btn btn-outline-info' %>
  <%= link_to 'Delete', task_path(@task),
    method: :delete, data: { confirm: "Are you sure?" },
    class:'btn btn-outline-danger' %>
  <%= @presenter.start_finish_justification_button? %>
</div>

<%= link_to 'Go back', board_lists_path(@task.list.board_id) %>